### ISSUE TITLE
go2nix seems overly greedy

### ISSUE THREAD

**Issue by rushmorem** [kamilchm/go2nix#24]
Sometimes `go2nix` requires additional packages beyond those required by `go build` to actually build. For example, if you are packaging [coredns], a `go get -d ./` is sufficient to fetch all its dependancies for building their main package. However, running `go2nix save` requires some other packages before it can successfully compile the `Nix` expressions.

I ran into this a number of times while packaging for `Nix`, I ended up creating a script that downloads these extra requirements while `go2nix save`ing:-
```bash
#!/bin/sh

while true; do
	missing_package=$(go2nix save 2>&1 | awk -F'"' '{print $2}')
	[[ -z $missing_package ]] && exit 0
	go get -d -v $missing_package
	echo "Finished downloading $missing_package"
done
``` 

[coredns]: https://github.com/miekg/coredns

**Comment by kamilchm** [comment]
Thx for reporting this.
I plan to write tests for `go2nix` with few packages (i will look at coredns too) as a examples to address https://github.com/kamilchm/go2nix/issues/21.
I'll come back to this next week.

**Comment by kamilchm** [comment]
I found the problem with `coredns` - unused imports in https://github.com/miekg/coredns/blob/master/core/coredns.go
`go get` and `go build` won't go as deep as `go2nix` into these dependencies.
Go package management in it's glory :(

**Comment by kamilchm** [comment]
Got it, `go2nix` doesn't include packages provided in `vendor` of dependent packages, eg. `k8s.io/kubernetes/vendor` in this case.

**Comment by kamilchm** [comment]
Fixed in https://github.com/kamilchm/go2nix/releases/tag/v1.1.1
