### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by nhooyr** [kamilchm/go2nix#27]
`go get github.com/kamilchm/go2nix` gives:

`$GOPATH/src/github.com/kamilchm/go2nix/nix.go:109: undefined: Asset`

edit: seems to build fine with nix though. as in I add `pkgs.go2nix` to `environment.systemPackages`

**Comment by kamilchm** [comment]
Unfortunately programs that use `go-bindata` to embed assets can't be build with `go get` :/
What you can do is:
```
$ go get -d github.com/kamilchm/go2nix
$ pushd $GOPATH/src/github.com/kamilchm/go2nix
$ go generate
$ go build
$ cp $GOPATH/src/github.com/kamilchm/go2nix/go2nix $GOPATH/bin
$ popd
```
This should work the same as `go get` for regular packages.

**Comment by kamilchm** [comment]
After some thoughts, I think I can check in generated assets.go to make installation easier.
