### ISSUE TITLE
selector ‘go2nix’ matches no derivations

### ISSUE THREAD

**Issue by siddharthist** [kamilchm/go2nix#33]
The command in the README isn't working for me:
```
code/nixpkgs > nix-env -i go2nix
error: selector ‘go2nix’ matches no derivations
```
```
code/nixpkgs > nixos-version
17.03.git.3d80ba4 (Gorilla)
```

**Comment by kamilchm** [comment]
What abut `nix-env -iA go2nix`?

**Comment by siddharthist** [comment]
Still no, actually:
```
code/nixpkgs > git log | head -n 1 
commit 83df0e7b18f3856d631a66243f5ad57571b1306c
code/nixpkgs > nix-env -iA go2nix
error: attribute ‘go2nix’ in selection path ‘go2nix’ not found
```
Sorry if this a dumb error on my part.

**Comment by kamilchm** [comment]
You may need to say explicitly where is your `nixpkgs` repo like:
```
code/nixpkgs > nix-env -f . -iA go2nix
```

**Comment by siddharthist** [comment]
Huh, that worked! Thanks! I wonder why I had an issue... Seems like the package name is `go1.7-go2nix-1.1.1`, maybe that's part of it.

**Comment by kamilchm** [comment]
You can try to do https://github.com/NixOS/nix/issues/487#issuecomment-251756794 if you don't want to use `-f` all the time.

**Comment by siddharthist** [comment]
@kamilchm Thanks, that is confusing behavior :confused:
