### ISSUE TITLE
Crash with apparent JSON parse error

### ISSUE THREAD

**Issue by crclark** [kamilchm/go2nix#36]
I get the following output when I try to run `go2nix save` on the `go2nix` repository, with the latest master:

```
2016/10/17 14:59:35 invalid character 'u' looking for beginning of object key string
```

I tried this on OS X and Ubuntu. On OS X, I installed from source (version is 1.2.0-devel). On Ubuntu, I installed from the 16.09 channel using Nix.

When I try this on NixOS, it does work.

**Comment by kamilchm** [comment]
Hi, I've tried to reproduce it on Ubuntu 16.04 and 16.09 channel but it works fine for me. See https://gist.github.com/kamilchm/04b6087d8702b9a5edc3576ce3051166
Could you try to reproduce it using Vagrant?

**Comment by crclark** [comment]
I've had a lot of difficulty reproducing this with Vagrant. I'm going to close this and reopen if I can reproduce later.
