### ISSUE TITLE
leaps packaging fail

### ISSUE THREAD

**Issue by qknight** [kamilchm/go2nix#42]
i've tried multipe hours to get a `deps.nix` from leaps which i once even got working.

can you please advice how to approach the problem?

https://github.com/Jeffail/leaps

# concept

```
nix-shell -p go2nix git go
mkdir /tmp/l
cd /tmp/l
export GOPATH=`pwd`:`pwd`/vendor/
go get github.com/jeffail/leaps/cmd/...
cd src/github.com/jeffail/leaps/cmd/leaps
go2nix save
```

# deps.nix
```
# This file was generated by go2nix.
[
]

```

**Comment by kamilchm** [comment]
You don't need to add `vendor` to `GOPATH`. This would be included automatically.
Other thing is that when I run https://github.com/kamilchm/go2nix/blob/master/test/test_leaps.sh it fails on trying to find `bytes` package that shouldn't be processed at all.

**Comment by kamilchm** [comment]
I also did:
```
nix-shell -p go2nix git go
cd `mktemp -d`
export GOPATH=`pwd`
go get github.com/jeffail/leaps/cmd/...
cd src/github.com/jeffail/leaps/cmd/leaps
go2nix save
```

and I got `deps.nix`:
```
# This file was generated by go2nix.
[
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "5d997795f7bb1d2de5edc1f5d64af2562401c82d";
      sha256 = "1kcqn4lninavavlspcn6gn621cvn2skyc9jwfwy8052ys8p1r2kg";
    };
  }
]
```

Could you try it exactly like that?

**Comment by qknight** [comment]
yeah, that works!
i want to add this example to the README.md soon.

thanks!
