### ISSUE TITLE
go2nix save takes too long?

### ISSUE THREAD

**Issue by kamilchm** [kamilchm/go2nix#43]
Doing `go2nix save` for `github.com/jeffail/leaps/cmd/leaps` like described in https://github.com/kamilchm/go2nix/issues/42#issuecomment-259020818 takes:
```
real	6m3.184s
user	0m14.674s
sys	0m2.782s
```

Is there something unwanted happens in `go2nix` code?

**Comment by kamilchm** [comment]
After few runs with profiler, it looks like it's more a `go/build` problem than `go2nix`.

**Comment by chris-martin** [comment]
Might be worth throwing this into the documentation somewhere. I was about to file an issue with the same question.

**Comment by chris-martin** [comment]
It's been running for a half hour now, though... Suppose there's any chance this isn't going to terminate?
