### ISSUE TITLE
Help generating a package for Leanote

### ISSUE THREAD

**Issue by pjones** [kamilchm/go2nix#63]
I'm unfamiliar with Go development but would like to create a Nix package for [leanote](https://github.com/leanote/leanote).

From what I gather it's a web application using the [Revel](https://github.com/revel/revel) framework.  Running the application involves installing the `revel` binary and then executing it, providing it the path to `leanote`:

```
revel run github.com/leanote/leanote
```

In this case, I'm not really sure if `go2nix` can generate a package for me.  Or perhaps I need to generate two packages, one for revel and one for leanote.  Either way, I'm confused how to create a package that would allow someone to ultimately run the command above (or some wrapped variation of it).

Any help would be greatly appreciated.  Thank you.

**Comment by pjones** [comment]
Hmm, perhaps I need a `postInstall` that does [this](http://revel.github.io/manual/deployment.html#build-local).

**Comment by orivej** [comment]
You should import `revel` and `leanote` with go2nix as two separate packages, and alter `buildPhase` of `leanote` to use `${revel.bin}/bin/revel build` instead of `go build`.

**Comment by pjones** [comment]
Thanks for the suggestion @orivej, I'll give that a try.

**Comment by pjones** [comment]
Breaking things up into two packages does appear to be the best solution.  Thank you.
