### ISSUE TITLE
Mention dep2nix

### ISSUE THREAD

**Issue by kamilchm** [kamilchm/go2nix#72]
https://github.com/nixcloud/dep2nix

**Comment by adamtulinius** [comment]
Does this mean we should be using dep2nix instead of the v2 branch of go2nix for packaging our dep-based application?

**Comment by kamilchm** [comment]
I would use `dep2nix` for now.
I also encourage Go users to look into [vgo modules](https://tip.golang.org/cmd/go/#hdr-Modules__module_versions__and_more) and maybe start a new `vgo2nix` tool than can replace `go2nix` in the future.

**Comment by adamtulinius** [comment]
Thanks for the update. :-)

**Comment by orivej** [comment]
@adisbladis has started https://github.com/adisbladis/vgo2nix

**Comment by adamtulinius** [comment]
> @adisbladis has started https://github.com/adisbladis/vgo2nix

Amazing how Google currently doesn't return that link as a result when searching for vgo2nix. Thanks for sharing it.
